# src/Propagators/Hamiltonian.jl


"""
    Hamiltonian

Module responsible for the numerical propagation of orbital dynamics using Hamilton canonical equations. 

It operates strictly in the phase space of Delaunay action-angle variables, enabling the direct numerical integration of average or osculating 
Hamiltonians symbolically derived in computer algebra systems.

"""
module Hamiltonian


using ..Types
using ..Coordinates
using ..ReadEquations
using ..PropagatorUtils
using Unitful, UnitfulAstro
using DifferentialEquations
using StaticArrays
using RecursiveArrayTools: ArrayPartition
using DataFrames
using LinearAlgebra 

export run_hamiltonian_simulation

"""
    run_hamiltonian_simulation(; ics, equation_func, perturbation_params, tspan, t_vector, propagator_options)

Executes the numerical integration of an orbital system using Hamilton differential equations.

This function maps the initial planetary conditions (Keplerian elements and mean anomaly) into Delaunay 
momenta (L, G, H) and coordinates (l, g, h). It ensures type stability for the numerical solver by converting 
uninitialized physical parameters into zero values. The integration is performed using the provided symbolically 
derived dynamics function.

# Keyword Arguments
- `ics::Vector{<:Types.InitialPlanetaryConditions}`: A vector containing the initial conditions defined by classical orbital elements and the mean anomaly.
- `equation_func::Function`: The compiled dynamics function containing the analytical Hamiltonian equations of motion, usually generated by the symbolic processor.
- `perturbation_params::Types.PhysicalParams`: Structure holding the physical parameters (gravity harmonics, third body data, etc.) required to evaluate the symbolic equations.
- `tspan::Tuple`: The simulation time span (t_start, t_end).
- `t_vector::AbstractVector`: A vector of specific time points. If `saveat` is enabled in the propagator options, the solver evaluates the solution exactly at these intervals.
- `propagator_options::Types.PropagatorOptions`: Structure defining the numerical solver, absolute and relative tolerances, and event callbacks (such as Poincare sections).

# Returns
- `Vector{Types.SimulationResult}`: A vector containing the complete simulation result object for each evaluated initial condition, including raw Poincare map data if requested.
"""
function run_hamiltonian_simulation(; 
    ics::Vector{<:Types.InitialPlanetaryConditions}, 
    equation_func::Function,           
    perturbation_params::Types.PhysicalParams, 
    tspan::Tuple,
    t_vector::AbstractVector,
    propagator_options::Types.PropagatorOptions
    )

    all_results = Types.SimulationResult[]

    # 1. prepares parameters: replaces Dict with NamedTuple (NECESSARY FOR THE SOLVER)
    # transforms the PhysicalParams struct into a named tuple of Float64
    # if the field is nothing, it becomes 0.0, as this ensures type stability.
    p_val = NamedTuple{fieldnames(typeof(perturbation_params))}(
        map(fieldnames(typeof(perturbation_params))) do f
            val = getfield(perturbation_params, f)
            isnothing(val) ? 0.0 : Float64(val)
        end
    )

    for (ic_index, ic) in enumerate(ics)
        println("--- Hamiltonian Simulation (Delaunay): Orbit $ic_index ---")
        
        # 2. extraction of initial conditions
        mu_val = p_val.mu 
        
        a0 = ustrip(u"km", ic.a0)
        e0 = ic.e0
        i0 = ustrip(u"rad", ic.i0)
        h0 = ustrip(u"rad", ic.h0) 
        g0 = ustrip(u"rad", ic.g0) 
        l0 = ustrip(u"rad", ic.l0) 

        # 3. calculation of canonical moments (L, G, H)
        L0 = sqrt(mu_val * a0)
        G0 = L0 * sqrt(max(0.0, 1.0 - e0^2))
        H0 = G0 * cos(i0)

        # initial state: [L, G, H, l, g, h]
        u0_delaunay = [L0, G0, H0, l0, g0, h0]
        
        cb_poincare, p_data = PropagatorUtils.setup_poincare_callback(propagator_options, Types.HamiltonEquations())
        
        prob = ODEProblem(equation_func, u0_delaunay, tspan, p_val)
        
        solver_opts = Dict{Symbol, Any}(
            :reltol => propagator_options.reltol,
            :abstol => propagator_options.abstol,
            :maxiters => propagator_options.maxiters,
            :saveat => propagator_options.saveat ? t_vector : Float64[],
            :progress => true,
            :callback => cb_poincare
        )

        if !isnothing(propagator_options.dt)
            dt_s = propagator_options.dt isa Unitful.Time ? 
                ustrip(u"s", propagator_options.dt) : 
                Float64(propagator_options.dt)
            solver_opts[:dt] = dt_s
        end
        
        sol = solve(prob, propagator_options.integrator; solver_opts...)
               
        result = Types.SimulationResult(
            solution = sol, 
            elements = nothing,
            initial_conditions = ic, 
            parameters = perturbation_params,
            propagator = propagator_options.propagator,
            equation_type = Types.HamiltonEquations(),
            poincare_raw = p_data[:raw_states] 
        )
        push!(all_results, result)        
    end # end for
    
    return all_results
end

end # end of module