# src/Propagators/LagrangePE.jl

"""
    LagrangePE

Module responsible for the numerical propagation of orbital dynamics using Lagrange Planetary Equations. 

It operates directly in the state space of classical Keplerian orbital elements (a, e, i, Omega, omega, M), allowing for the integration of analytical variations of parameters derived symbolically.


"""
module LagrangePE # Lagrange Planerary Equations

using ..Types
using ..Coordinates
using ..ReadEquations
using ..PropagatorUtils
using Unitful, UnitfulAstro
using DifferentialEquations
using RecursiveArrayTools: ArrayPartition
using DataFrames
using LinearAlgebra 
using StaticArrays

export run_lpe_simulation

"""
    run_lpe_simulation(; ics, equation_func, perturbation_params, tspan, t_vector, propagator_options)

Executes the numerical integration of an orbital system using Lagrange Planetary Equations.

This function utilizes initial planetary conditions (Keplerian elements and mean anomaly) directly 
as the state vector `[a, e, i, h, g, l]`. It ensures type stability for the numerical solver by converting 
uninitialized physical parameters into zero values before feeding them to the compiled dynamics function.

# Keyword Arguments
- `ics::Vector{<:Types.InitialPlanetaryConditions}`: A vector containing the initial conditions defined by classical orbital elements and the mean anomaly.
- `equation_func::Function`: The compiled dynamics function containing the analytical Lagrange equations of motion, usually generated by the symbolic processor.
- `perturbation_params::Types.PhysicalParams`: Structure holding the physical parameters (gravity harmonics, etc.) required to evaluate the symbolic equations.
- `tspan::Tuple`: The simulation time span `(t_start, t_end)`.
- `t_vector::AbstractVector`: A vector of specific time points. If `saveat` is enabled in the propagator options, the solver evaluates the solution exactly at these intervals.
- `propagator_options::Types.PropagatorOptions`: Structure defining the numerical solver, absolute and relative tolerances, and event callbacks (such as Poincare sections).

# Returns
- `Vector{Types.SimulationResult}`: A vector containing the complete simulation result object for each evaluated initial condition, including raw Poincare map data if requested.
"""
function run_lpe_simulation(;
    ics::Vector{<:Types.InitialPlanetaryConditions}, 
    equation_func::Function,           
    perturbation_params::Types.PhysicalParams, 
    tspan::Tuple,
    t_vector::AbstractVector,
    propagator_options::Types.PropagatorOptions
    )

    all_results = Types.SimulationResult[]

    # 1. prepares parameters: replaces Dict with NamedTuple (NECESSARY FOR THE SOLVER)
    # transforms the PhysicalParams struct into a named tuple of Float64
    # if the field is nothing, it becomes 0.0, as this ensures type stability.
    p_val = NamedTuple{fieldnames(typeof(perturbation_params))}(
        map(fieldnames(typeof(perturbation_params))) do f
            val = getfield(perturbation_params, f)
            isnothing(val) ? 0.0 : Float64(val)
        end
    )

    for (ic_index, ic) in enumerate(ics)
        println("--- Lagrangian Simulation (Keplerian): Orbit $ic_index ---")
        
        # 2. extraction of initial conditions        
        a0 = ustrip(u"km", ic.a0)
        e0 = ic.e0
        i0 = ustrip(u"rad", ic.i0)
        h0 = ustrip(u"rad", ic.h0) 
        g0 = ustrip(u"rad", ic.g0) 
        l0 = ustrip(u"rad", ic.l0) 

        println("Initial Conditions: a0=$(a0), e0=$(e0), i0=$(uconvert(u"°", i0)), h0=$(uconvert(u"°", h0)), g0=$(uconvert(u"°", g0)), l0=$(uconvert(u"°", l0))")

        # initial state: [a, e, i, h, g, l]
        u0_keplerian = [a0, e0, i0, h0, g0, l0]

        # universal event configuration
        cb_poincare, p_data = PropagatorUtils.setup_poincare_callback(propagator_options, Types.LagrangeEquations())
        
        prob = ODEProblem(equation_func, u0_keplerian, tspan, p_val)
        
        solver_opts = Dict{Symbol, Any}(
            :reltol => propagator_options.reltol,
            :abstol => propagator_options.abstol,
            :maxiters => propagator_options.maxiters,
            :saveat => propagator_options.saveat ? t_vector : [],
            :progress => true,
            :callback => cb_poincare
        )
        
        sol = solve(prob, propagator_options.integrator; solver_opts...)
               
        result = Types.SimulationResult(
            solution = sol, 
            elements = nothing, # Preenchido no PostProcessing
            initial_conditions = ic, 
            parameters = perturbation_params, # aqui passa o PhysicalParams 
            propagator = propagator_options.propagator,
            equation_type = Types.LagrangeEquations(),
            poincare_raw = p_data[:raw_states]
        )
        push!(all_results, result)

        
    end # end for
    
    return all_results

end

end # end of module