# src/Models/ReadEquations.jl

"""
    ReadEquations

module responsible for bridging the gap between symbolic computer algebra systems (cas) like maxima and the high-performance numerical solvers in julia.

it parses raw text files containing symbolic expressions, sanitizes the syntax, and uses metaprogramming to compile them into highly optimized, type-stable julia functions and ordinary differential equation (ode) systems.

"""
module ReadEquations

using ..Types


export load_equation_function, load_ode_system, build_analytical_function

"""
    _parse_maxima_file(filepath::String)

internal helper function that reads a raw text file generated by maxima, sanitizes the syntax (e.g., replacing `%pi` with `pi` and `%e` with `exp(1.0)`), 
and parses it into a valid julia abstract syntax tree (ast).

# arguments
- `filepath::String`: path to the text file containing the maxima output.

# returns
- `Vector{Any}`: an array of parsed julia expressions representing the body content.
"""
function _parse_maxima_file(filepath::String)
    @info "Reading equation file" file=basename(filepath) source="ReadEquations"
    
    # 1. read and sanitize
    s = read(filepath, String)
    s = replace(s, r"[\r\n]+" => " ")
    s = replace(s, "\\" => "")
    s = replace(s, "%pi" => "pi")
    s = replace(s, "%e" => "exp(1.0)")
    s = replace(s, "atan2(" => "atan(")
    s = replace(s, r"%([0-9a-z]+)" => s"var_\1") # handles %o1, %o2...

    # 2. parse
    expr = try
        Meta.parse(s)
    catch err
        error("Syntax error when reading Maxima's equation: $err")
    end

    # 3. toplevel treatment
    if expr isa Expr && expr.head == :toplevel
        real_args = filter(x -> !(x isa LineNumberNode), expr.args)
        expr = isempty(real_args) ? error("Empty expression") : 
               (length(real_args) == 1 ? real_args[1] : Expr(:block, real_args...))
    end

    # 4. optimized block treatment
    body_content = []
    
    if expr isa Expr && expr.head == :call && expr.args[1] == :block
        raw_statements = expr.args[3:end] # skips 'block' and local vars
        for stmt in raw_statements
            # converts ':' to '='
            if stmt isa Expr && stmt.head == :call && stmt.args[1] == :(:)
                push!(body_content, Expr(:(=), stmt.args[2], stmt.args[3]))
            else
                push!(body_content, stmt)
            end
        end
    else
        push!(body_content, expr)
    end

    # 5. ensures correct return (tuple if it's a vector)
    last_expr = body_content[end]
    if last_expr isa Expr && last_expr.head == :vect
        body_content[end] = Expr(:tuple, last_expr.args...)
    end

    return body_content
end

"""
    load_equation_function(filepath; vars_from_p, pos_vars, keyword_vars, p_type)

reads a symbolic equation from a file and compiles it into a standalone julia function.

this is primarily used to load analytical functions such as the hamiltonian, generating functions for lie series transformations, or specific equilibrium root conditions. the resulting function automatically maps the physics parameter structure (`p`) into the local scope to ensure high performance and zero allocations during repeated evaluations.

# arguments
- `filepath::AbstractString`: path to the `.txt` file containing the maxima output.

# keyword arguments
- `vars_from_p::Vector{Symbol}`: list of parameter symbols (e.g., `:mu`, `:j2`) to explicitly extract from the `PhysicalParams` struct.
- `pos_vars::Vector{Symbol}`: list of positional variables to alias dynamically. defaults to `Symbol[]`.
- `keyword_vars::Vector{Symbol}`: list of keyword arguments to alias dynamically. defaults to `Symbol[]`.
- `p_type::Type`: the expected type for the parameter struct. defaults to `Types.PhysicalParams`.

# returns
- `Function`: a compiled julia function with the signature `(a, e, i, L_mean, G_mean, H_mean, p; kwargs...)`.
"""
function load_equation_function(
    filepath::AbstractString; 
    vars_from_p::Vector{Symbol},
    pos_vars::Vector{Symbol} = Symbol[], 
    keyword_vars::Vector{Symbol} = Symbol[], 
    p_type::Type = Types.PhysicalParams
    )::Function

    # 1. gets the body from maxima
    body_content = _parse_maxima_file(filepath)

    # 2. prepares parameter extraction from the struct (mu, j2, c22...)
    assigns_p = [:( local $s = getfield(p, $(QuoteNode(s))) ) for s in vars_from_p]

    # 3. function construction
    # we add 't=0.0' in the keyword arguments so the function accepts 't'
    func_expr = :((a, e, i, L_mean, G_mean, H_mean, p::$(p_type); 
                    l=0.0, g=0.0, h=0.0, f=0.0, r=0.0, lambda_sun=0.0, tau=0.0, t=0.0) -> begin
        
        # --- 1. injects physical parameters ---
        $(assigns_p...)
        sqr(x) = x^2

        # --- 2. safe fixed aliases ---
        L = L_mean; G = G_mean; H = H_mean;
        L_0 = L_mean; G_0 = G_mean; H_0 = H_mean;
        l_0 = l; g_0 = g; h_0 = h;
        
        # internally defines 't' for maxima to find
        # if the expression has 't', it will use the passed value or 0.0
        local t_val = t 
        
        # --- 3. dynamic mapping (legacy support) ---
        $([:($s = $(Symbol(replace(string(s), "_mean" => "", "_0" => "")))) 
            for s in pos_vars if !(s in [:a, :e, :i, :p, :L, :G, :H])]...)
            
        
        $([:($s = $(Symbol(replace(string(s), "_mean" => "", "_0" => "")))) 
            for s in keyword_vars if !(s in [:l, :g, :h, :f, :r, :lambda_sun, :tau, :t])]...)

        # --- 4. equation body ---
        $(Expr(:block, body_content...))
    end)

    return eval(func_expr)
end

"""
    load_ode_system(::Types.HamiltonEquations, filepath; vars_from_p)

compiles a set of symbolic differential equations into an optimized, in-place mutating function `f(du, u, p, t)` strictly compatible with `DifferentialEquations.jl`.

this specific dispatch handles delaunay action-angle variables `[L, G, H, l, g, h]`, computing the necessary keplerian conversions internally (with mathematical domain safeguards) and assigning the evaluated rates to the derivative vector `du`.

# arguments
- `::Types.HamiltonEquations`: dispatch type indicating the delaunay phase space.
- `filepath::AbstractString`: path to the text file containing the compiled maxima differential equations.

# keyword arguments
- `vars_from_p::Vector{Symbol}`: symbols of the physical parameters required by the equations.

# returns
- `Function`: the in-place mutating ode function.
"""
function load_ode_system(::Types.HamiltonEquations, filepath::AbstractString; vars_from_p::Vector{Symbol})::Function
    
    # 1. file parsing
    body_content = _parse_maxima_file(filepath)

    # 2. get the last element (derivative vector)
    results_vec = pop!(body_content) 

    # prepare parameters for namedtuple
    assigns_p = [:( local $s = hasfield(typeof(p), $(QuoteNode(s))) ? getfield(p, $(QuoteNode(s))) : 0.0 ) for s in vars_from_p]

    # ode function assembly
    func_expr = :(function (du, u, p, t)
        # 1. unpack state
        L = u[1]; G = u[2]; H = u[3]
        l = u[4]; g = u[5]; h = u[6]

        # 2. unpack parameters
        $(assigns_p...)

        # 3. definition of robust helpers (avoids domainerror)
        sqr(x) = x^2
        
        # local redefinition of sqrt to protect against numerical noise
        sqrt(x) = Base.sqrt(Base.max(0.0, x))

        # calculation of auxiliary elements that maxima might need
        # this prevents julia from using the constant 'e' (2.718) instead of eccentricity
        a = sqr(L) / mu
        e = sqrt(1.0 - sqr(G/L))
        
        # protection for inclination calculation
        cos_i = Base.clamp(H/G, -1.0, 1.0)
        sin_i = sqrt(1.0 - sqr(cos_i))
        i = Base.acos(cos_i)

        # 4. equation body (calculation of temporary variables %1, %2...)
        $(Expr(:block, body_content...))

        # 5. assignment to du (maxima order [dl, dg, dh, dl, dg, dh] -> julia [dl, dg, dh, dl, dg, dh])
        # du[1:3] are momenta (l, g, h), du[4:6] are coordinates (l, g, h)
        du[1] = $(results_vec.args[4]) 
        du[2] = $(results_vec.args[5])
        du[3] = $(results_vec.args[6])
        du[4] = $(results_vec.args[1])
        du[5] = $(results_vec.args[2])
        du[6] = $(results_vec.args[3])

        return nothing
    end)

    return eval(func_expr)
end

"""
    load_ode_system(::Types.LagrangeEquations, filepath; vars_from_p)

compiles a set of symbolic differential equations into an optimized, in-place mutating function `f(du, u, p, t)` strictly compatible with `DifferentialEquations.jl`.

this specific dispatch handles classical lagrange planetary equations, operating directly on the keplerian elements parameterized by the mean anomaly `[a, e, i, h, g, l]`.

# arguments
- `::Types.LagrangeEquations`: dispatch type indicating the lagrange phase space.
- `filepath::AbstractString`: path to the text file containing the compiled maxima differential equations.

# keyword arguments
- `vars_from_p::Vector{Symbol}`: symbols of the physical parameters required by the equations.

# returns
- `Function`: the in-place mutating ode function.
"""
function load_ode_system(::Types.LagrangeEquations, filepath::AbstractString; vars_from_p::Vector{Symbol})::Function
    body_content = _parse_maxima_file(filepath)
    results_vec = pop!(body_content) 
    assigns_p = [:( local $s = hasfield(typeof(p), $(QuoteNode(s))) ? getfield(p, $(QuoteNode(s))) : 0.0 ) for s in vars_from_p]

    func_expr = :(function (du, u, p, t)
        # 1. lagrange state: [a, e, i, h, g, l]
        a, e, i = u[1], u[2], u[3]
        h, g, l = u[4], u[5], u[6]

        $(assigns_p...)

        sqr(x) = x^2
        sqrt(x) = Base.sqrt(Base.max(0.0, x))

        $(Expr(:block, body_content...))

        # direct lagrange assignment
        du[1] = $(results_vec.args[1]); du[2] = $(results_vec.args[2]); du[3] = $(results_vec.args[3])
        du[4] = $(results_vec.args[4]); du[5] = $(results_vec.args[5]); du[6] = $(results_vec.args[6])
        return nothing
    end)

    return eval(func_expr)
end


"""
    build_analytical_function(eq_func; target=:i)

wraps a compiled analytical expression into a callable anonymous function designed for evaluating equilibrium maps over a 2d parameter grid.

it dynamically maps the input variables `v1` and `v2` to the correct orbital elements based on the requested `target`. for example, if `target` is `:i`, it assumes the underlying function computes `cos(i)` and automatically applies the `acos` function bounded by a numerical clamp to prevent domain errors.

# arguments
- `eq_func::Function`: the base expression or function to be evaluated.

# keyword arguments
- `target::Symbol`: the target orbital element being solved. supports `:i` (inclination) or `:e` (eccentricity). defaults to `:i`.

# returns
- `Function`: an anonymous mapping function with the signature `(v1, v2, p)`.
"""
function build_analytical_function(eq_func::Function; target::Symbol=:i)
    # target=:generic) simple function without acos
    expr = eq_func

    # 4. returns an anonymous function that julia can "compile"
    # the order of arguments (v1, v2) depends on who is the independent variable in your mapper
    if target == :i
        return (v1, v2, p) -> begin
            # if the maxima expression is for cos_i, we apply acos
            # v1=a, v2=e (or vice-versa, depending on your mapper)
            # here we do the local binding for the expression to understand 'a' and 'e'
            a, e = v1, v2 
            val_cos = eval(expr) # note: in a production environment we would use runtimegeneratedfunctions
            return acos(clamp(val_cos, -1.0, 1.0))
        end
    elseif target == :e
        return (v1, v2, p) -> begin
            a, i = v1, v2
            return eval(expr)
        end
    else
        return (v1, v2, p) -> begin
            e, i = v1, v2
            return eval(expr)
        end
    end
end

end # end of module